export const PURCHASE_SHOW_LIST = 'PURCHASE_SHOW_LIST';
export const PURCHASE_SHOW_CARD = 'PURCHASE_SHOW_CARD';
export const GET_PURCHASE_LIST_REQUEST = 'GET_PURCHASE_LIST_REQUEST';
export const GET_PURCHASE_LIST_SUCCESS = 'GET_PURCHASE_LIST_SUCCESS';
export const GET_PURCHASE_LIST_FAILURE = 'GET_PURCHASE_LIST_FAILURE';

export const PURCHASE_SHOW_CARD_REQUEST = 'PURCHASE_SHOW_CARD_REQUEST';
export const PURCHASE_SHOW_CARD_SUCCESS = 'PURCHASE_SHOW_CARD_SUCCESS';
export const PURCHASE_SHOW_CARD_FAILURE = 'PURCHASE_SHOW_CARD_FAILURE';
export const PURCHASE_SHOW_CARD_CLOSE = 'PURCHASE_SHOW_CARD_CLOSE';

export const PURCHASE_ADD_SHOW_CARD = 'PURCHASE_ADD_SHOW_CARD';
export const PURCHASE_ADD_SAVE_REQUEST = 'PURCHASE_ADD_SAVE_REQUEST';
export const PURCHASE_ADD_SAVE_SUCCESS = 'PURCHASE_ADD_SAVE_SUCCESS';
export const PURCHASE_ADD_SAVE_FAILURE = 'PURCHASE_ADD_SAVE_FAILURE';

export const CURRENT_VIEW_TYPE_LIST = 'CURRENT_VIEW_TYPE_LIST';
export const CURRENT_VIEW_TYPE_CARD = 'CURRENT_VIEW_TYPE_CARD';
export const CURRENT_VIEW_TYPE_CARD_PURCHASE_POSITION = 'CURRENT_VIEW_TYPE_CARD';

export const GET_PURCHASE_POSITION_LIST_REQUEST = 'GET_PURCHASE_POSITION_LIST_REQUEST';
export const GET_PURCHASE_POSITION_LIST_SUCCESS = 'GET_PURCHASE_POSITION_LIST_SUCCESS';
export const GET_PURCHASE_POSITION_LIST_FAILURE = 'GET_PURCHASE_POSITION_LIST_FAILURE';

export const PURCHASE_POSITION_SHOW_CARD_REQUEST = 'PURCHASE_POSITION_SHOW_CARD_REQUEST';
export const PURCHASE_POSITION_SHOW_CARD_SUCCESS = 'PURCHASE_POSITION_SHOW_CARD_SUCCESS';
export const PURCHASE_POSITION_SHOW_CARD_FAILURE = 'PURCHASE_POSITION_SHOW_CARD_FAILURE';

export const PURCHASE_NOTIFICATION_SHOW_LIST = "PURCHASE_NOTIFICATION_SHOW_LIST";